# Generated by Django 3.1 on 2020-10-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_auto_20201022_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='nds_3dcrt_misdelivery',
            name='code_101106',
            field=models.SmallIntegerField(null=True),
        ),
    ]
