version: '3'

services:
  db:
    image: mysql:8
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: NDS
      MYSQL_ROOT_PASSWORD: AA-koala123456
      MYSQL_USER: django
      MYSQL_PASSWORD: django123
    # volumes:
    #   - ./data:/var/lib/mysql
    tmpfs:
      - /var/lib/mysql  # Use in-memory filesystem


  web:
    build: .
    command: sh -c "/docker-entrypoint.sh"
    ports:
      - "8000:8000"
    volumes:
    - ./graph:/code/utils/plGraphs
    depends_on:
      - db